package org.hedgewars.android.data

import java.io.File

/**
 * Writes default gamepad bindings into the engine's settings.ini.
 *
 * On MOBILE builds the engine ignores per-team `ebind` commands
 * (uInputHandler.pas SetBinds is desktop-only); the only binding channel is
 * the `[Binds]` section of <user-prefix>/Config/settings.ini, read by
 * loadBinds('dbind', …) from InitDefaultBinds. Key names are raw SDL joystick
 * elements: j<dev>a<axis>u|d, j<dev>h<hat>u|r|d|l, j<dev>b<button>.
 *
 * SDL2's Android backend exposes the D-pad as hat 0, the left stick as axes
 * 0/1 and A/B/X/Y as buttons 0-3.
 */
object BindsWriter {

    // One physical key per command (the engine unbinds the previous key when
    // a command is bound again). D-pad is SDL hat 0 on Android (AXIS_HAT_X/Y,
    // the standard mapping for modern gamepads); button indices follow
    // SDLControllerManager.getButtonMask: 0=A 1=B 2=X 3=Y 7=Start 8=ThumbL
    // 9=ThumbR 10=L1 11=R1.
    private val GAMEPAD_BINDS = linkedMapOf(
        // D-pad: walk + aim
        "+left" to "j0h0l",
        "+right" to "j0h0r",
        "+up" to "j0h0u",
        "+down" to "j0h0d",
        // face buttons
        "+attack" to "j0b2",   // X: fire (hold for power)
        "hjump" to "j0b0",     // A: high jump
        "ljump" to "j0b1",     // B: long jump
        "ammomenu" to "j0b3",  // Y: weapon menu
        // shoulders: precise aim / weapon timer
        "+precise" to "j0b10", // L1
        "timer 3" to "j0b11",  // R1
        // start = pause, thumb click = switch hedgehog
        "pause" to "j0b7",
        "switch" to "j0b9",
    )

    /**
     * (Re)writes settings.ini with the [Binds] section, preserving nothing:
     * the file is fully owned by the frontend on this platform.
     */
    fun write(settingsIni: File, gamepadEnabled: Boolean) {
        settingsIni.parentFile?.mkdirs()
        val sb = StringBuilder()
        sb.append("; generated by the Hedgewars Android frontend\n")
        sb.append("[Binds]\n")
        // Android back button (SDL "AC Back" -> engine key name ac_back):
        // open the engine's quit-confirmation instead of doing nothing.
        sb.append("quit=ac_back\n")
        if (gamepadEnabled) {
            // loadBinds parses "<command>=<keyname>" and turns it into
            // "dbind <keyname> <command>" (uInputHandler.pas loadBinds/addBind)
            for ((command, key) in GAMEPAD_BINDS) {
                sb.append(command).append('=').append(key).append('\n')
            }
        }
        settingsIni.writeText(sb.toString())
    }
}
