package org.hedgewars.android.data

import java.io.File

/**
 * Writes default gamepad bindings into the engine's settings.ini.
 *
 * On MOBILE builds the engine ignores per-team `ebind` commands
 * (uInputHandler.pas SetBinds is desktop-only); the only binding channel is
 * the `[Binds]` section of <user-prefix>/settings.ini, read by
 * loadBinds('dbind', …) from InitDefaultBinds. Key names are SDL controller
 * elements: j<dev>a<axis>u|d and j<dev>b<button>.
 *
 * The engine reads gamepads through SDL's game controller API, so the
 * numbering is the SEMANTIC Xbox-style standard — identical on every pad,
 * mapped by SDL itself (gamecontrollerdb, or built on Android from the
 * device's reported capabilities):
 *
 *   axes:    0=LeftX 1=LeftY 2=RightX 3=RightY 4=LeftTrigger 5=RightTrigger
 *   buttons: 0=A 1=B 2=X 3=Y 4=Back 5=Guide 6=Start 7=ThumbL 8=ThumbR
 *            9=L1 10=R1 11..14=DPad up/down/left/right
 *
 * The engine names the positive direction of an axis `u` and the negative
 * one `d`; Android's stick Y axes point DOWN. Triggers report 0..32767 with
 * rest at 0, so only their `u` half can ever fire (~60% pull) — their `d`
 * half is dead by construction, no polarity trap anymore.
 *
 * One command may be bound to SEVERAL keys (d-pad button + stick axis): the
 * engine's rebind-displacement is disabled on MOBILE (uInputHandler.pas
 * addBind). Each KEY must appear at most once.
 */
object BindsWriter {

    private val GAMEPAD_BINDS = listOf(
        // D-pad: walk + aim
        "+up" to "j0b11",
        "+down" to "j0b12",
        "+left" to "j0b13",
        "+right" to "j0b14",
        // Left stick: same commands as the d-pad
        "+right" to "j0a0u",
        "+left" to "j0a0d",
        "+down" to "j0a1u",
        "+up" to "j0a1d",
        // Right stick: camera
        "+cur_r" to "j0a2u",
        "+cur_l" to "j0a2d",
        "+cur_d" to "j0a3u",
        "+cur_u" to "j0a3d",
        // face buttons
        "+attack" to "j0b2",   // X: fire (hold for power). In the weapon menu: pick
        "hjump" to "j0b0",     // A: high jump. In the weapon menu: pick
        "ljump" to "j0b1",     // B: long jump. In the weapon menu: close
        "ammomenu" to "j0b3",  // Y: weapon menu
        // Shoulders, as requested by field testers: R side = grenade fuse,
        // L side = bounciness. Both commands self-guard on non-applicable
        // weapons. L2 (trigger) holds precise aim.
        "timer_u" to "j0b10",  // R1: cycle the grenade fuse 1-5 s
        "timer_u" to "j0a5u",  // R2: same
        "+bounce" to "j0b9",   // L1: cycle bounciness
        "+precise" to "j0a4u", // L2 held: precise aim
        // start = pause, left thumb click = switch hedgehog
        "pause" to "j0b6",
        "switch" to "j0b7",    // ThumbL click
        // Right thumb click confirms the target of aimed weapons (teleport,
        // homing bee, air strikes…): you aim the crosshair with that very
        // stick, clicking it places the target. The engine's `put` is a no-op
        // outside choose-target mode, and in the weapon menu it picks the
        // highlighted weapon — consistent everywhere, dead key nowhere.
        "put" to "j0b8",       // ThumbR click
    )

    /**
     * (Re)writes settings.ini with the [Binds] section, preserving nothing:
     * the file is fully owned by the frontend on this platform.
     */
    fun write(settingsIni: File, gamepadEnabled: Boolean) {
        settingsIni.parentFile?.mkdirs()
        val sb = StringBuilder()
        sb.append("; generated by the Hedgewars Android frontend\n")
        sb.append("[Binds]\n")
        // Android back button (SDL "AC Back" -> engine key name ac_back):
        // open the engine's quit-confirmation instead of doing nothing.
        sb.append("quit=ac_back\n")
        if (gamepadEnabled) {
            // loadBinds parses "<command>=<keyname>" and turns it into
            // "dbind <keyname> <command>" (uInputHandler.pas loadBinds/addBind)
            for ((command, key) in GAMEPAD_BINDS) {
                sb.append(command).append('=').append(key).append('\n')
            }
        }
        settingsIni.writeText(sb.toString())
    }
}
